---
- name: Configure plugins
  delegate_to: localhost
  notify: Upload config
  community.general.xml:
    pretty_print: true
    path: "{{ local_file }}"
    xpath: "{{ xpath }}/plugins"
    value: "{{ opnsense_plugins | join(',') }}"

- name: Install Packages
  community.general.pkgng:
    name: "{{ opnsense_plugins }}"
    state: present
