---
- name: "[PRE-TASK] Fetch config.xml from remote host"
  ansible.builtin.fetch:
    src: "{{ config_file }}"
    dest: "{{ local_file }}"
    flat: true

- name: Configure plugins
  delegate_to: localhost
  notify: Upload config
  community.general.xml:
    pretty_print: true
    path: "{{ local_file }}"
    xpath: "{{ xpath }}/plugins"
    value: "{{ opnsense_plugins | join(',') }}"

- name: Install Packages
  community.general.pkgng:
    name: "{{ opnsense_plugins }}"
    state: present

- name: Flush Handlers
  ansible.builtin.meta: flush_handlers
